[pytest]
testpaths = tests
cache_dir = .cache/pytest
markers =
    gui: tests that require GUI dependencies like dearpygui or (future) nicegui
filterwarnings =
    ignore:Could not find the number of physical cores.*:UserWarning:joblib.externals.loky.backend.context
